######################################################################
# Automatically generated by qmake (2.01a) Mon May 10 17:15:16 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += rageform.h
FORMS += rageform.ui
SOURCES += main.cpp rageform.cpp
